name: Python Tests

on:
  pull_request:

jobs:
  # Fast core tests for development workflow (target: <5 minutes)
  fast-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.13.5'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run flake8
        run: flake8 src tests
      - name: Run mypy
        run: mypy src
      - name: Run fast core tests (skips expensive ML optimization)
        run: python tests/run_tests.py -k "not test_public_functions_are_decorated and not test_notebook"
      - name: Run notebook structure validation
        run: python tests/run_tests.py tests/test_notebooks.py::test_notebooks_exist -v

  # Full integration tests (manual trigger for releases)
  # Uncomment the lines below to enable the full integration suite when needed
  # full-tests:
  #   runs-on: ubuntu-latest
  #   if: github.event.pull_request.title contains '[FULL-INTEGRATION]'
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-python@v4
  #       with:
  #         python-version: '3.13.5'
  #     - name: Install dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install -r requirements.txt
  #     - name: Run full integration suite
  #       run: python tests/run_tests.py --integration
